{
    'name': 'QACO Audit Management System',
    'version': '17.0.1.0.0',
    'summary': 'Pakistan-focused audit engagement lifecycle and compliance framework',
    'sequence': 10,
    'description': 'Provides Pakistani regulatory alignment for audit engagements, onboarding, risk, and independence workflows.',
    'category': 'Accounting',
    'license': 'LGPL-3',
    'author': 'QACO Pakistan',
    'website': 'https://www.qaco.com.pk',
    'depends': ['base', 'mail', 'contacts', 'account', 'calendar', 'project', 'documents'],
    'data': [
        'security/audit_security.xml',
        'security/ir.model.access.csv',
        'data/industry_data.xml',
        'data/audit_data.xml',
        'templates/engagement_letter_template.xml',
        'templates/email_templates.xml',
        'views/audit_menus.xml',
        'views/res_partner_views.xml',
        'views/audit_engagement_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'qaco_audit/static/src/css/audit_style.css',
            'qaco_audit/static/src/js/audit_engagement.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}