from . import employee_designation
from . import employee_docs
from . import employee_experience
from . import employee_family_reference
from . import hr_employee_transfer
from . import hr_employee_public
from . import hr_leave
from . import hr_public_holiday
from . import leave_adjustment
from . import leave_adjustment_approval
from . import leave_allowance
from . import leave_condonation
from . import leave_summary
from . import qaco_absence
from . import qaco_employees
from . import qaco_region
from . import scheduled_employee_progress_report
from . import transfer_cc_recipient
from . import unallocated_employee_notification
from . import unallocated_employee_recipient
from . import weekly_employee_report
from . import daily_attendance_report
