{
    "name": "AI Audit Management",
    "summary": "ISA-compliant audit suite with OpenAI automation",
    "description": "Complete Pakistan ISA-aligned audit lifecycle with AI assisted planning, execution, reporting, and archival controls.",
    "author": "Prime360 Audit Suite",
    "website": "https://www.example.com",
    "category": "Accounting/Audit",
    "version": "1.0.0",
    "license": "OPL-1",
    "depends": ["base", "mail", "web", "documents", "hr", "account"],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/ai_settings_data.xml",
        "data/ir_cron.xml",
        "views/menu.xml",
        "views/client_acceptance_views.xml",
        "views/engagement_letter_views.xml",
        "views/audit_plan_views.xml",
        "views/internal_control_views.xml",
        "views/substantive_test_views.xml",
        "views/completion_review_views.xml",
        "views/final_report_views.xml",
        "views/archival_views.xml",
        "views/ai_settings_views.xml",
        "views/dashboard_views.xml",
        "views/ocr_views.xml",
        "views/evidence_index_views.xml",
        "reports/report_templates.xml",
        "reports/report_actions.xml",
    ],
    "demo": [
        "data/demo_data.xml",
    ],
    "assets": {},
    "application": True,
    "installable": True,
    "auto_install": False,
}
