{
    "name": "QACO Planning Phase (ISA)",
    "summary": "ISA-aligned audit planning: strategy, materiality, risk assessment, checklist, information requisitions, timeline",
    "version": "17.0.1.11",
    "author": "QACO",
    "license": "LGPL-3",
    "category": "Accounting/Auditing",
    "depends": ["base", "mail", "qaco_audit", "qaco_client_onboarding"],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/industry_sector_data.xml",
        "data/information_requisition_templates.xml",
        "data/mail_templates.xml",
        "data/cron_jobs.xml",
        "views/planning_phase_views.xml",
        "views/planning_phase_actions.xml",
        "views/industry_sector_views.xml",
        "views/qaco_audit_form_extend.xml",
        "views/planning_v2_views.xml",
        "views/engagement_details_views.xml",
        "views/risk_assessment_views.xml",
        "views/menu_view.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
}
