-- Candidate Patch (COMMENTED by default)
-- Generated by scripts/generate_candidate_patch.py
-- Review carefully before applying. Use --db <dbname> to include DB-driven suggestions.

-- No DB provided. Run with --db <dbname> to produce DB-driven candidate patch suggestions.

-- Additional safe suggestions (manual review recommended):
-- 1) Ensure 'web_responsive' is installed and loaded to avoid 'is_redirect_home' errors. If the field was missing in DB and code provides it, install or upgrade the module.
-- 2) Do not delete ir_model rows without manual verification; use the review table approach above.

