#!/usr/bin/env python3
"""
Scan repository for disallowed Unicode bullets and smart quotes in Python-evaluated files.
Exit 0 if none found, otherwise print offending files and exit 1.

Usage: scripts/check_no_unicode_bullets.py [path]
"""
import sys
from pathlib import Path

DISALLOWED = ['\u2022', '\u201c', '\u201d', '\u2018', '\u2019']
# file globs to check - python and manifest files
GLOBS = ["**/*.py", "**/__manifest__.py"]

root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parents[1]

errors = []
for glob in GLOBS:
    for p in root.glob(glob):
        # skip autogenerated or third-party directories when appropriate
        if "venv" in p.parts or "node_modules" in p.parts:
            continue
        try:
            txt = p.read_text(encoding='utf-8')
        except Exception as e:
            print(f"Warning: couldn't read {p}: {e}", file=sys.stderr)
            continue
        for ch in DISALLOWED:
            if ch in txt:
                errors.append((str(p), ch))

if errors:
    print("Found disallowed unicode characters in the following files:")
    for f, ch in errors:
        print(f" - {f}: {repr(ch)}")
    print("\nPlease remove these characters from Python or manifest files. See docs: scripts/check_no_unicode_bullets.py")
    sys.exit(1)

print("No disallowed Unicode bullets or smart quotes found in Python/manifest files.")
sys.exit(0)
