-- Candidate Disable & Optimization SQL (COMMENTED by default)
-- Generated by scripts on $(date)
-- Review carefully. This file contains conservative, reversible actions to:
--  1) Disable crons and server actions referencing missing models
--  2) Provide safe optimization steps (indexes, VACUUM/ANALYZE)
-- Each section includes UNDO guidance. Do not run without backup and review.

-- =====================================
-- SECTION A: Disable problematic crons (examples)
-- =====================================
-- Disable by name pattern (review the names first):
-- UPDATE ir_cron SET active = false WHERE name ILIKE '%Unallocate Employees%';
-- UPDATE ir_cron SET active = false WHERE name ILIKE '%Pending Transfers%';
-- UPDATE ir_cron SET active = false WHERE name ILIKE '%Employee Transfer%';

-- Disable by model (recommended when model is missing in registry):
-- UPDATE ir_cron SET active = false WHERE model IN ('hr.employee.transfer', 'unallocated.employee.recipient');

-- UNDO:
-- UPDATE ir_cron SET active = true WHERE name ILIKE '%Unallocate Employees%';
-- UPDATE ir_cron SET active = true WHERE model IN ('hr.employee.transfer', 'unallocated.employee.recipient');


-- =====================================
-- SECTION B: Disable server actions referencing missing models
-- =====================================
-- Example: Make action inert by setting state=code and raising a warning
-- UPDATE ir_actions_server SET state = 'code', code = 'raise Warning(\'Disabled pending model restoration\')' WHERE model IN ('hr.employee.transfer');

-- UNDO: restore from export or backup; alternatively set state and code to previous values.


-- =====================================
-- SECTION C: Safe DB optimization queries
-- =====================================
-- Note: Run these during maintenance windows. Prefer VACUUM FREEZE/ANALYZE for large DBs offline.

-- 1) Create helpful indexes (idempotent)
CREATE INDEX IF NOT EXISTS idx_ir_model_model ON ir_model (model);
CREATE INDEX IF NOT EXISTS idx_ir_model_fields_model ON ir_model_fields (model_id, name);
CREATE INDEX IF NOT EXISTS idx_ir_cron_model ON ir_cron (model);
CREATE INDEX IF NOT EXISTS idx_ir_actions_server_model ON ir_actions_server (model);

-- 2) Vacuum & analyze (conservative)
VACUUM ANALYZE ir_model;
VACUUM ANALYZE ir_model_fields;
VACUUM ANALYZE ir_cron;
VACUUM ANALYZE ir_actions_server;
VACUUM ANALYZE;

-- 3) Recompute sequences if needed
-- SELECT setval('ir_model_id_seq', (SELECT COALESCE(MAX(id),0) FROM ir_model));
-- SELECT setval('ir_model_fields_id_seq', (SELECT COALESCE(MAX(id),0) FROM ir_model_fields));

-- 4) Clean old logs (conservative retention 30 days)
-- DELETE FROM ir_logging WHERE create_date < NOW() - INTERVAL '30 days';

-- UNDO for optimization: Ensure you have backup; deleted logs can't be restored.


-- =====================================
-- SECTION D: Recommended follow-up queries (diagnostics)
-- =====================================
-- List crons referencing models that are not present in repo_models.txt
-- SELECT id, name, model FROM ir_cron WHERE model IS NOT NULL AND model NOT IN (SELECT model FROM ir_model) ORDER BY id;

-- List server actions referencing missing models
-- SELECT id, name, model FROM ir_actions_server WHERE model IS NOT NULL AND model NOT IN (SELECT model FROM ir_model) ORDER BY id;

-- Archive candidate ir_model entries to a review table (non-destructive)
-- CREATE TABLE IF NOT EXISTS scripts_ir_model_review (id serial PRIMARY KEY, model text, notes text, created_at timestamptz DEFAULT now());
-- INSERT INTO scripts_ir_model_review (model, notes) SELECT model, 'candidate for review' FROM ir_model WHERE model NOT IN (SELECT model FROM repo_model_list); -- repo_model_list would need to be populated from repo

-- =====================================
-- End of file
