#!/usr/bin/env python3
"""Generate a DRY-RUN SQL file with suggested non-destructive fixes for missing models, crons, and server actions.
Usage:
  python scripts/generate_dryrun_sql.py --out dryrun_suggestions.sql [--db <dbname>] [--psql psql]

If --db is supplied the script will attempt to run safe SELECT queries via psql to collect DB evidence; otherwise it will run repository-only checks and create a commented SQL file with suggested actions and UNDO statements.
"""
import argparse
import subprocess
import shlex
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / 'scripts'
OUT_DIR.mkdir(exist_ok=True)

parser = argparse.ArgumentParser()
parser.add_argument('--db', help='Database name to query (optional)')
parser.add_argument('--psql', default='psql', help='psql executable path')
parser.add_argument('--out', default=str(OUT_DIR / 'dryrun_suggestions.sql'))
args = parser.parse_args()

out_path = Path(args.out)

# Helper functions

def run_psql(query: str):
    cmd = f"{args.psql} -d {shlex.quote(args.db)} -t -c {shlex.quote(query)}"
    try:
        out = subprocess.check_output(cmd, shell=True, stderr=subprocess.DEVNULL)
        return out.decode('utf-8').strip()
    except Exception as e:
        return None

# Collect repo models
repo_models = sorted([m.strip() for m in subprocess.check_output([sys.executable, 'scripts/compare_repo_models.py']).decode('utf-8').splitlines() if m.strip()])

# Start building the dry-run SQL content
lines = []
lines.append('-- Dry-run suggested SQL (NON-DESTRUCTIVE by default)')
lines.append('-- Generated by scripts/generate_dryrun_sql.py')
lines.append('-- Review carefully before applying. Each change below includes an UNDO statement.')
lines.append('-- If you want to apply changes, run the SQL after review or use the safer orchestrator script.')
lines.append('\n')

# If DB provided, collect DB evidence
if args.db:
    lines.append(f'-- DB evidence collection for database: {args.db}\n')
    # Models present in DB but not in repo
    q = "SELECT model FROM ir_model ORDER BY model;"
    db_models_output = run_psql(q)
    if db_models_output is None:
        lines.append('-- Could not run psql queries. Ensure psql is available and credentials are setup.')
    else:
        db_models = [r.strip() for r in db_models_output.splitlines() if r.strip()]
        missing_in_repo = [m for m in db_models if m not in repo_models]
        if missing_in_repo:
            lines.append('-- Models present in DB but not in repo (candidates for review):')
            for m in missing_in_repo:
                lines.append(f'--   {m}')
            lines.append('\n')
            # Suggest to archive by inserting into a review table rather than deleting
            lines.append('-- SUGGESTED: Insert candidates into a review table for manual inspection')
            lines.append("-- CREATE TABLE IF NOT EXISTS scripts_ir_model_review (id serial PRIMARY KEY, model text, notes text, created_at timestamptz DEFAULT now());")
            for m in missing_in_repo:
                lines.append(f"-- INSERT INTO scripts_ir_model_review (model, notes) VALUES ('{m}', 'Detected by dry-run; review before delete');")
            lines.append('\n')
        else:
            lines.append('-- No DB-only models detected (every DB model exists in repo)\n')

    # Crons referencing missing models
    q = "SELECT id, name, model FROM ir_cron WHERE model IS NOT NULL ORDER BY id;"
    crons_output = run_psql(q)
    if crons_output:
        lines.append('-- ir_cron entries (id | name | model):')
        for ln in crons_output.splitlines():
            if ln.strip():
                lines.append(f'--   {ln.strip()}')
        lines.append('\n')
        lines.append('-- SUGGESTED: Disable specific crons that reference models missing in repo or DB by id:')
        lines.append('-- UPDATE ir_cron SET active = false WHERE id = <cron_id>;')
        lines.append('-- UNDO: UPDATE ir_cron SET active = true WHERE id = <cron_id>;')
        lines.append('\n')

    # Server actions referencing missing models
    q = "SELECT id, name, model FROM ir_actions_server ORDER BY id;"
    sa_output = run_psql(q)
    if sa_output:
        lines.append('-- ir_actions_server entries (id | name | model):')
        for ln in sa_output.splitlines():
            if ln.strip():
                lines.append(f'--   {ln.strip()}')
        lines.append('\n')
        lines.append('-- SUGGESTED: Change server action to inert code and add UNDO code. Example:')
        lines.append('-- UPDATE ir_actions_server SET state = ''code'', code = ''# disabled by dry-run - review'' WHERE id = <id>;')
        lines.append("-- UNDO: Restore original code from backup table or revision control")
        lines.append('\n')

else:
    # No DB: produce repo-only suggestions
    lines.append('-- NOTE: No DB was provided. Run with --db <dbname> to gather DB evidence and produce more targeted SQL suggestions.\n')
    lines.append('-- Suggestion: Run scripts/check_db_vs_repo.ps1 or scripts/safe_odoo_fix.sh on the server to gather DB info.\n')

# Common quick win suggestions (non-destructive)
lines.append('-- Quick wins (non-destructive suggestions)')
lines.append('-- 1) Ensure web_responsive is installed and its models imported to resolve is_redirect_home error:')
lines.append("--    Ensure web_responsive module is listed in addons_path and imported; to undo, remove the field from code or revert the module installation.")
lines.append('-- 2) Do NOT mass-delete ir_model rows; instead, archive candidates to a review table as above.\n')

# Write a human-readable report file
report_path = OUT_DIR / 'dryrun_report.txt'
with report_path.open('w', encoding='utf-8') as rf:
    rf.write('\n'.join(lines))

# Also write the SQL file (commented dry-run)
with out_path.open('w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f'DRY-RUN SQL written to: {out_path}')
print(f'Report written to: {report_path}')
print('\nReview both files and run on staging with --db <dbname> to collect DB evidence or provide the DB dump for offline analysis.')
