from typing import Any, Callable, Iterable, TypeVar

F = TypeVar('F', bound=Callable[..., Any])

def depends(*names: str) -> Callable[[F], F]: ...

def constrains(*names: str) -> Callable[[F], F]: ...

def model(func: F) -> F: ...

def ondelete(param: str) -> Callable[[F], F]: ...
